### ISSUE TITLE
how would you use goback() function in kv file

### ISSUE THREAD

**Issue by ps2229** [kulothunganug/kivy-lazy-loading-template#3]
AKSilverAppbar:
            max_height: dp(250)
            title: '    Record'
            left_action_items: [["arrow-left", **lambda _:setattr(root.manager,'go_back')]]**
            pin_top: True
            hide_toolbar: True
            radius: dp(20)
            toolbar_bg: 0,204/255,238/255,1

how to go about the lambda function in this case.

**Comment by kulothunganug** [comment]
This question isn't about this `template`.

But here is the fix 🙂
```kv
AKSilverAppbar:
    left_action_items: [["arrow-left", root.app_bar_callback]]
```
```py
......
    def app_bar_callback(self, *args):
        self.manager.goback()
```
