### ISSUE TITLE
Is it possible to add hot reload?

### ISSUE THREAD

**Issue by ono24id** [kulothunganug/kivy-lazy-loading-template#5]
is it possible to add hot reload like in this repository https://github.com/JennaSys/kivy_hotreload?

**Comment by ono24id** [comment]
Hi, this is my version to be able to hot reload individual kv screen with kivymd added
https://github.com/ptprotechbit/kivymd-basic-app

Thanks!

**Comment by kulothunganug** [comment]
It is quite unstable in most situations, so no idea about adding it.

But you can check out https://github.com/kulothunganug/kvhot which will **hot-restart** the application. This will work on any kind of project structure you want and not restricts the user.
